<a href="https://colab.research.google.com/github/pauldebanshu19/AI-Lab/blob/main/Google_Colab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import statistics
print(statistics.mean([1, 3, 5, 7, 9,11,13]))
print(statistics.mean([1, 3, 5, 7, 9,11]))
print(statistics.mean([-11,5.5,-3.4,7.1,-9,22]))

7
6
1.8666666666666667


In [ ]:
import statistics
print(statistics.median([1, 3, 5, 7, 9,11,13]))
print(statistics.median([1, 3, 5, 7, 9,11]))
print(statistics.median([-11,5.5,-3.4,7.1,-9,22]))

7
6.0
1.05


In [ ]:
import statistics
print(statistics.mode([1, 3, 3, 3, 5, 7, 7, 9, 11]))
print(statistics.mode([1, 1, 3, -5, 7, -9, 11]))
print(statistics.mode(['red','green','blue','red']))

3
1
red


In [ ]:
import statistics
print(statistics.stdev([1, 3, 5, 7, 9,11]))
print(statistics.stdev([2,2.5,1.25,3.1,1.75,2.8]))
print(statistics.stdev([-11,5.5,-3.4,7.1]))
print(statistics.stdev([1,30,50,100]))

3.7416573867739413
0.6925797186365383
8.414471660973927
41.67633221226007


In [ ]:
import statistics
print(statistics.variance([1, 3, 5, 7, 9,11]))
print(statistics.variance([2,2.5,1.25,3.1,1.75,2.8]))
print(statistics.variance([-11,5.5,-3.4,7.1]))
print(statistics.variance([1,30,50,100]))

14
0.47966666666666663
70.80333333333333
1736.9166666666667


In [ ]:
import numpy as np
array1=np.arange(8)
print("Original array:\n",array1)

array2=np.arange(8).reshape(2,4)
print("\narray reshaped with 2 rows and 4 columns:\n",array2)

array3=np.arange(8).reshape(4,2)
print("\narray reshaped with 4 rows and 2 columns:\n",array3)

array4=np.arange(8).reshape(2,2,2)
print("\nOriginal array reshaped to 3D:\n",array4)

Original array:
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns:
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 4 rows and 2 columns:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
import pandas as pd
data = { 'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj', 'Ravi', 'Natasha', 'Riya'],
         'Age': [17,17,18,17,18,17,17],
         'Gender': ['M','F','M','M','M','F','F'],
         'Marks': [90, 76,'NaN', 74, 65, 'NaN', 71]  }

df = pd.DataFrame(data)
df

Name  Age Gender Marks
0      Jai   17      M    90
1   Princi   17      F    76
2   Gaurav   18      M   NaN
3     Anuj   17      M    74
4     Ravi   18      M    65
5  Natasha   17      F   NaN
6     Riya   17      F    71

In [ ]:
df['Gender']=df['Gender'].map({'M':0,'F':1}).astype(float)
df

Name  Age  Gender Marks
0      Jai   17     0.0    90
1   Princi   17     1.0    76
2   Gaurav   18     0.0   NaN
3     Anuj   17     0.0    74
4     Ravi   18     0.0    65
5  Natasha   17     1.0   NaN
6     Riya   17     1.0    71